### ISSUE TITLE
ShootSpeakerCommand Brake mode backwards

### ISSUE THREAD

**Issue by mandrews281** [entech281/Robot2024#171]
It appears the brake mode for the ShooterSubsystem in the ShootSpeakerCommand is backwards.  When the command initializes it sets BrakeMode OFF making the speed harder to control, and when the command ends, it sets it ON which puts more stress on the motors, pulleys, etc. to stop the shooter.  I think it should be the reverse.  initialize -> ON, end -> OFF.

**Comment by dcowden** [comment]
Added this to the Anderson project

**Comment by mandrews281** [comment]
Done in JTM_Shooting branch
