### ISSUE TITLE
Provide power requirements for cameras and orange pis to electrical

### ISSUE THREAD

**Issue by dcowden** [entech281/Robot2024#58]
* can we find a battery that can provide 3A at 5V?
* is that battery legal to use? 
* is it legal to use two of them?
* what cables could carry that much current?

**Comment by WhyDoesGodDoThis** [comment]
Change to giving battery mount requirements to give to mechanical.

**Comment by WhyDoesGodDoThis** [comment]
pick battery pack from list of three.
