### ISSUE TITLE
Intake Subsystem

### ISSUE THREAD

**Issue by WhyDoesGodDoThis** [entech281/Robot2024#75]
Needs to control the motor that runs the intake rollers in the false bumper.

1 motor.
The expected input should just be a state enum that has the options reverse, forward, and stopped.
The expected output is the current state enum.
Commands will be across multiple subsystems on a separate issue.
Not much can be done off robot with this system.

**Comment by dcowden** [comment]
This includes:

* control motor
* RunIntakeCommand 
*   --> start when operator pushes toggle, stop when operator releases toggle
*   ( cancelled when NoteDetectedCommand is run)
