### ISSUE TITLE
Create Controls Spec

### ISSUE THREAD

**Issue by dcowden** [entech281/Robot2024#76]
Before we code subsystems, we should create a 1 page controls specification, with signoff from student leaders and mentors. 

This spec should include:

- a picture of the proposed robot, with the names of the systems identified 
- operating controls: control type, buttons and what they do
- automations and how they are connected
- which controls are operator and which ones are driver
- subsystems enumerated, with definitions for input object and output object
- signoff by student leaders
- signoff by mentors

**Comment by dcowden** [comment]
update: @mandrews281 suggested also more specifically that we pay particular attention to exactly what automated behaviors are desired, and (probably ) their relative priority.  We have heard talk of these:

- auto align to target, either as a button, or while driving while a button is held
- drop arm when driving, for safety. 
- slow down before walls, for safety
- intake to shooter transfer
- shoot at speaker
- shoot at amp
- align on colored game piece on the floor
- button to tell the robot all things are homed

And of course, there is the subject of auto routines. what routines do we do first? then what are our stretch goals?

**Comment by mandrews281** [comment]
I tried drafting something at a high level.  I came up with some key categories.  Here's some examples:

**BEHAVIOR:** 
When the robot has a note, always face the designated target (amp, speaker)
**WHY:**
1. Speeds up scoring
2. Provides feedback to Driver & Operator
**CONFLICTS WITH:**
1. Avoiding defensive robots with spin moves
2. Seeing the AprilTags
**UNKNOWNS:**
1. How do the Operator/Drive designate the target?
2. Should the driver have an override?  If so, in what cases?  How do we go back to auto_facing?

**BEHAVIOR:** 
When driving, keep the super-structure down.
**WHY:** 
Avoid damage
**CONFLICTS WITH:** 
1. Shooting
2. Continuous auto-aiming
**UNKNOWNS:**
1. How do we decide that the driver/operator want to auto-aim and shoot?

**Comment by dcowden** [comment]
I love the inclusion of 'why' in these.
Andrew, can you incorporate mikes suggestions too?
